<<<<<<< HEAD
# Generated by Django 3.1.5 on 2021-02-05 11:52
=======
# Generated by Django 3.1.3 on 2021-02-11 13:36
>>>>>>> 08a3bf94c59ede2b2a34a89367068f3f1bc43a5e

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ident', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('done', models.CharField(choices=[('doing', 'Doing'), ('done', 'Done')], max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('membros', models.CharField(max_length=250)),
                ('entrega', models.DateField()),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metas.membro')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metas.setor')),
            ],
        ),
        migrations.AddField(
            model_name='membro',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metas.setor'),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oquefoifeito', models.CharField(max_length=255)),
                ('oquevaiserfeito', models.CharField(blank=True, max_length=255)),
                ('impedimento', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fk_meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metas.meta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metas.membro')),
            ],
        ),
    ]
