# Generated by Django 3.1.3 on 2021-02-12 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meta',
            name='deletado',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meta',
            name='porcentagem',
            field=models.IntegerField(default=0, max_length=3),
            preserve_default=False,
        ),
    ]
