# Generated by Django 3.1.3 on 2021-02-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setor',
            name='ident',
            field=models.CharField(default='comunicacao', max_length=50),
            preserve_default=False,
        ),
    ]
